// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD34M-Qc5-Vr9-QneHCfceAxjcjGZqhOe4',
    appId: '1:539195871126:web:8ca7630ffd248aaed3d7b7',
    messagingSenderId: '539195871126',
    projectId: 'fit-now-8788d',
    authDomain: 'fit-now-8788d.firebaseapp.com',
    storageBucket: 'fit-now-8788d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_hPP53hu0T_H-aRBJxse9XvXnQ57GSs',
    appId: '1:539195871126:android:1745678f6752f13ad3d7b7',
    messagingSenderId: '539195871126',
    projectId: 'fit-now-8788d',
    storageBucket: 'fit-now-8788d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRTN6VvGXfvR4wCFTsc6hN2V5O2Us9CQ',
    appId: '1:539195871126:ios:6d296628f043ef10d3d7b7',
    messagingSenderId: '539195871126',
    projectId: 'fit-now-8788d',
    storageBucket: 'fit-now-8788d.firebasestorage.app',
    androidClientId: '539195871126-1ckc6tr2994kn3g49d2aqnnggaodm3q5.apps.googleusercontent.com',
    iosClientId: '539195871126-mca4ftlejhvhkc5rdqi9opnpfb3j9vl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitNow.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIRTN6VvGXfvR4wCFTsc6hN2V5O2Us9CQ',
    appId: '1:539195871126:ios:1dcf651008876556d3d7b7',
    messagingSenderId: '539195871126',
    projectId: 'fit-now-8788d',
    storageBucket: 'fit-now-8788d.firebasestorage.app',
    androidClientId: '539195871126-1ckc6tr2994kn3g49d2aqnnggaodm3q5.apps.googleusercontent.com',
    iosClientId: '539195871126-nsqo1f3gug7bk0pp889cgjvkpado2jr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD34M-Qc5-Vr9-QneHCfceAxjcjGZqhOe4',
    appId: '1:539195871126:web:8ca7630ffd248aaed3d7b7',
    messagingSenderId: '539195871126',
    projectId: 'fit-now-8788d',
    authDomain: 'fit-now-8788d.firebaseapp.com',
    storageBucket: 'fit-now-8788d.firebasestorage.app',
  );
}
